### ISSUE TITLE
Install Base Packages task failed

### ISSUE THREAD

**Issue by lumnikemel** [zoresvit/ansible-arch-linux#1]
Hi. I'm hoping you can shed some light on why this might have failed on my config. As far as I can tell, the only difference between our setups is that I am using VMware Workstation. I added the necessary variable and host_var to make that work.

However, when I tried to run this, I got a failure on installed the base_packages stating bad PGP signatures. Did you have this problem, too? I had to add this command just before that task `pacman-key --populate archlinux`, and now it installs the packages correctly. 

I have a script that installs Arch via bash, and have never had a signature problem, but I also don't see anything missing in your playbook that would have caused the error. I'm just trying to figure out if I'm missing something more obvious.

**Comment by rkiyanchuk** [comment]
Did you have the issue when booted into Arch Linux Live CD, before executing `install.yml`?
Haven't seen such issue myself.

**Comment by rkiyanchuk** [comment]
Did you boot from the latest Arch Linux Live CD when you had this issue?
I haven't seen something like this myself.

**Comment by lumnikemel** [comment]
Hmm, Arch CD could be the problem. I'm using an install CD from January. I don't always download the latest one. Do you remember which month you were using when you had successfully tested the install?

**Comment by rkiyanchuk** [comment]
I usually download the latest available with [`make iso`](https://github.com/rkiyanchuk/ansible-arch-linux/blob/master/Makefile) from the repo.
